<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.1" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
	</ItemGroup>
	
	<!--Aqui estou utilizando o EF Core e o SQLite para haver persistência no arquivo .db-->
	<!--Aqui é o pacote Swashbuckle para poder implementar as funções Swagger e gerar a documentação-->
	<!--Aqui utilizei o EF Core Design para habilitar Migrations-->
	<!--OBSERVAÇÃO: Todos os comentários acima estão se referindo aos itens presentes no ItemGroup,
					estou colocando eles fora do bloco pois estava tendo erro ao aplicar "dotnet restore"-->
	
</Project>
